### ISSUE TITLE
Consider making a source package instead of directly building a .deb with dpkg-builddeb

### ISSUE THREAD

**Issue by lamby** [heartsucker/node-deb#1]
Whilst dpkg-builddeb certainly works, you are doing an awful lot of stuff manually and not able to use the multitude of useful packaging utilities by not ultimately building the package with dpkg-buildpackage. Did you reject this approach?

**Comment by ehartsuyker** [comment]
I slapped this together pretty quickly based off some existing maintainer scripts that exists for other projects and a couple of stackoverflow questions. There wasn't much design behind it other than "the current tool doesn't work." If you have links or examples, I'll definitely look at them.

**Comment by heartsucker** [comment]
Closing as won't fix until someone else asks for this feature.
