### ISSUE TITLE
Unable to run app

### ISSUE THREAD

**Issue by rocodesign** [heartsucker/node-deb#105]
I have created a simple node express server and packaged it with node-deb. The problem is that after installation when I run my app, I get the contents of my server.js file printed in the terminal instead of running it with node.

How do I get node to run my js file after installation.

Server has no dependencies as I'm bundling everything beforehand.

Is there also some trick to mark it as executable so I won't have to do manually after installation?

this is my node_deb config

```
"node_deb": {
    "init": "systemd",
    "install-strategy": "npm-install",
    "version": "0.1.0-beta",
    "entrypoints": {
      "daemon": "server.js"
    }
  }
```

Thanks

**Comment by rocodesign** [comment]
I have figured out the trick to make the file executable, it's actually not a trick at all :) the file permissions are just copied from the original.

I still have the problem of running the file with node.

Any help with that will be greatly appreciated

**Comment by heartsucker** [comment]
This is related to #66 which would help prevent these kind of errors. `node-deb` could warn or error during the build to help users in the future.

Does your `server.js` file start with something like `#!/usr/bin/node` or `#!/usr/bin/env node`? If not, the `bash` script in `templates/executable` will attempt to execute `server.js` as a `bash` file and probably immedaitely errors on something like `command require not found`.

**Comment by rocodesign** [comment]
Hey @heartsucker , thanks for the reply,

My server.js does not start with `node` and I'm not sure how to configure it to run with node. As you are saying it probably runs with bash and the contents of the file are just printed to the terminal screen.

What I ended up doing is creating a `server.sh` file that has the contents `node ./server.js` and put that into the daemon instead of server.js

now when I run the app manually it starts fine. but with the service I ran into another issue

```● sfr-collector-ui.service - Collector UI Application
   Loaded: loaded (/lib/systemd/system/sfr-collector-ui.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-03-01 17:14:38 EET; 2min 17s ago
  Process: 979 ExecStart=/usr/share/sfr-collector-ui/app/server.sh (code=exited, status=203/EXEC)
 Main PID: 979 (code=exited, status=203/EXEC)

Mar 01 17:14:38 romeo-XPS-15 systemd[1]: sfr-collector-ui.service: Service hold-off time over, scheduling restart.
Mar 01 17:14:38 romeo-XPS-15 systemd[1]: sfr-collector-ui.service: Scheduled restart job, restart counter is at 5.
Mar 01 17:14:38 romeo-XPS-15 systemd[1]: Stopped Collector UI Application.
Mar 01 17:14:38 romeo-XPS-15 systemd[1]: sfr-collector-ui.service: Start request repeated too quickly.
Mar 01 17:14:38 romeo-XPS-15 systemd[1]: sfr-collector-ui.service: Failed with result 'exit-code'.
Mar 01 17:14:38 romeo-XPS-15 systemd[1]: Failed to start Collector UI Application.
```

Anyway I'll search around and start another tread if I'm not able to figure it out.

Thanks for the great work on the `node-deb` tool.

**Comment by heartsucker** [comment]
Ok so this is the template for the unit file that gets generated

```ini
# This file was autogenerated by node-deb {{ node_deb_version }}

[Unit]
Description={{ node_deb_package_description }}
Requires=network.target

[Service]
Type=simple
EnvironmentFile=/etc/default/{{ node_deb_package_name }}
WorkingDirectory={{ node_deb_install_dir }}/{{ node_deb_package_name }}
ExecStart={{ node_deb_install_dir }}/{{ node_deb_package_name }}/app/{{ daemon_entrypoint }}
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
User={{ node_deb_user }}
PermissionsStartOnly=true

[Install]
WantedBy=multi-user.target
```

In the line `ExecStart`, it simply attempts to execute the file located at `daemon_entrypoint` and it does this by default with `bash` (or whatever your shell is). In order to let your OS know how to execute that file, it needs to have the shebang line (`#!/path/to/binary`) which in this case is `node`. This means that `server.js` needs to look like this

```js
#!/usr/bin/node

// your javascript code here
```

Can you try this?

**Comment by heartsucker** [comment]
Also I think something might be wrong on your side. Your error says this

```
/usr/share/sfr-collector-ui/app/server.sh
  Process: 979 ExecStart=/usr/share/sfr-collector-ui/app/server.sh (code=exited, status=203/EXEC)
```

Note that it ends in `.sh` and not `.js`. I think you have a typo somewhere?

**Comment by rocodesign** [comment]
@heartsucker  

I will try to add the `#!/usr/bin/node` to the js file.

I mentioned above that since I didn't know to add that the file I created a different file `server.sh` that just runs `node ./server.js`

I will try with your approach though.

Thanks again!

**Comment by heartsucker** [comment]
Ah ok got it. This packaging is rather delicate and does require some knowledge of how Debian-like OS-es will run things, so a user of this lib did something I didn't expect, things might go off the rails.

**Comment by rocodesign** [comment]
Anyway seems like adding the shebang fixed the issue with the service, thanks for the help, I'll test a bit more to find out if there are any issues.

Think it might work great now :) Cheers!

**Comment by heartsucker** [comment]
Cool, glad things worked out.
