### ISSUE TITLE
debian own repository & package size

### ISSUE THREAD

**Issue by empierre** [heartsucker/node-deb#19]
I've tried to setup my own debian package repository, but it seems there is an issue in size.

packages available here:
http://www.e-nef.com/domoticz/mdah/

$ du -s :
896     node-mydomoathome-0.0.31.deb

Installed-Size: 1164

error:
Les NOUVEAUX paquets suivants seront installés :
  MyDomoAtHome
0 mis à jour, 1 nouvellement installés, 0 à enlever et 1 non mis à jour.
Il est nécessaire de prendre 913 ko dans les archives.
Après cette opération, 1 192 ko d'espace disque supplémentaires seront utilisés.
Réception de : 1 http://www.e-nef.com/domoticz/mdah/  MyDomoAtHome 0.0.31 [913 kB]
915 ko réceptionnés en 0s (1 277 ko/s)
E: Impossible de récupérer http://www.e-nef.com/domoticz/mdah/./node-mydomoathome-0.0.31.deb  Taille incohérente

E: Impossible de récupérer certaines archives, peut-être devrez-vous lancer apt-get update ou essayer avec --fix-missing ?

**Comment by heartsucker** [comment]
@empierre What tool are you using to upload them to your Debian repo? And what version? We have hundreds of packages in our repo that were built with `node-deb`, and we've never seen this problem.

Also, can you run `uname -a` on both the host where the package was built and the repo host? I might be able to reproduce it.

Right now this sounds like it is a problem with other, unrelated software. `node-deb` uses `dpkg-build` under the hood, so I'm inclined to believe that `dpkg` is calculating the package size correctly.

**Comment by empierre** [comment]
my fault... I did sign in the wrong order and generate the packages... not sure but you may wan to include this too one day:

dpkg-sig -k xxxxxxxx --sign builder node-mydomoathome-$1.deb
dpkg-sig -k xxxxxxxx --sign builder node-mydomoathome-latest.deb
apt-ftparchive packages . > Packages
gzip -c Packages > Packages.gz
apt-ftparchive release . >Release
gpg --clearsign -o InRelease Release
gpg -abs -o Release.gpg Release
