### ISSUE TITLE
Installing to absolute path

### ISSUE THREAD

**Issue by vidstige** [heartsucker/node-deb#30]
First off, thanks for a very helpful package. How do I install a file to e.g. `/etc/myconfigfile.json`?

**Comment by heartsucker** [comment]
Hey @sanyatuning. Are you saying that you'd like to have some `<project-root>/some/path/myconfigfile.json` put into the Debian package so that at install time, it appears in `/etc/myconfigfile.json`?

**Comment by vidstige** [comment]
yes, exactly.

**Comment by vidstige** [comment]
For now I just changed the place were I refered to `/etc/` to instead refer to `/usr/share/tumel/app/`

**Comment by heartsucker** [comment]
I think this isn't supported at the moment. I think it might be possible to put things into `/etc/{app}/`, but I also feel like this might be a job for configuration management. Can you explain your use case?

**Comment by vidstige** [comment]
I see, yeah this was more of a question. Use case is I have a client connecting to a server. The client is inside this deb package. I want to keep the config file where it says what server and port to connect to in a config file. Usually on linux these are found in `/etc`. However, it would probably be a bad idea to edit files managed by apt. Best would be if I could copy a file to `/etc` in postinst. Can this be done then?

**Comment by heartsucker** [comment]
@vidstige Btw, this would be a use case for the `--extra-files` flag while allows you to drop files where ever you want on the file system. If you had a folder like
```
my-dir
  |- /etc/
     |- wat.txt
```

And did

```
node-deb --extra-files my-dir -- index.js
```

then `wat.txt` would end up at `/etc/wat.txt`.

**Comment by vidstige** [comment]
I see, then it was already supported. Thanks for the explanation. :+1:
