### ISSUE TITLE
`devDependencies` getting included

### ISSUE THREAD

**Issue by vidstige** [heartsucker/node-deb#34]
For some reason e.g. istanbul code coverage tools gets included even though it's in the `devDependencies` section of the package.json file. Not supported? Can I help out somehow?

**Comment by heartsucker** [comment]
Hmm. It copies the whole `node_modules` dir, and that includes the dev dependencies. I have gone back and forth with including the `node_modules` in the `.deb` and have left it there for the stable/immutable packages possible. You could just `rm -rf` the `node_modules` and have a lean `.deb`.

I'm not sure if there's a reasonable way to walk the dependency tree and rip out the things you don't want. I can take a peek later.

**Comment by vidstige** [comment]
No, I think it's great to include the `node_modules` so you have a complete stand-alone package. :+1: It's more all the extra bload that's not really needed. Walking the dep tree might be tricky... hmm, I'll just first run unit tests, then clear `node_modules/` and then run `npm install --production`

**Comment by vidstige** [comment]
Wait that didn't work as it also removed the devDependency `node-deb`... Oh well, I'll keep the bloat stuff in there for now ^^

**Comment by heartsucker** [comment]
I think a partial fix to this will be to add something to the docs to make devs aware of this.

**Comment by vidstige** [comment]
I made some further investigations and I think instead of including `node_modules/` by default, just include everything this command `npm ls --parseable --prod` 

For my project for example I get a nice flat list of all the prod dependencies. I'll try to make a pr if I ever get around.

**Comment by heartsucker** [comment]
Oh dang. This is perfect. I think I can have a fix ready in a few minutes. Good find!
