### ISSUE TITLE
systemd.service file is executable 

### ISSUE THREAD

**Issue by kmohrf** [heartsucker/node-deb#44]
hi,
the systemd service file in /etc/systemd/… that node-deb creates seems to be executable. systemd ignores it but issues a warning like this

```
Configuration file /etc/systemd/system/mirror-mirror.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```

the template itself is not executable so this may happen during packaging.

thanks

**Comment by heartsucker** [comment]
Hmm. This is an odd one. I'm just doing a `cp` of the file in the `templates` folder, so I'm not sure where the permissions are coming from. What OS are you building on? And what OS are you deploying on?

**Comment by kmohrf** [comment]
see [here](https://github.com/heartsucker/node-deb/issues/43#issuecomment-284093961) :)

**Comment by kmohrf** [comment]
the new build i created [on debian](https://github.com/heartsucker/node-deb/issues/43#issuecomment-284104092) suffers from the same issue.

**Comment by kmohrf** [comment]
maybe?
```sh
log_info 'Building Debian package'
chmod -R 0755 "$deb_dir"
```

**Comment by heartsucker** [comment]
Ah yes, that definitely was it. I forgot that I added that to fix permissions on the maintainer scripts. Thanks for catching that before I even had to sit down to debug. :)
