### ISSUE TITLE
Set `NODE_ENV` environment

### ISSUE THREAD

**Issue by vidstige** [heartsucker/node-deb#54]
As services started from packages built by node-deb _typically_ will run in production mode, the `NODE_ENV=production` environment should also be set. This is used by e.g. express to suppress stacktraces and other security sensitive information.

It could either be set inside `node_deb` in conjunction to computing the `start_command` string or we could juse prepend `NODE_ENV=production` in `templates/executable`.

**Comment by heartsucker** [comment]
As mentioned in https://github.com/heartsucker/node-deb/pull/22#r67354987, `NODE_ENV` should be left up to the developer / package maintainer. If this was set, it would be done in the `/etc/default/$package` file. This *should* be set by something like Chef and be package independent IMO, and even if not, the templates are overridable. Based on this, I'm closing this as "won't fix."

**Comment by vidstige** [comment]
I see, that makes sense :+1:
