### ISSUE TITLE
TravisCI support

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/node-deb#56]
I have been shipping crap software lately. Let the FOSS gods save me from myself as I offer up my humble package to the pedestal of judgement that is TravisCI.

**Comment by vidstige** [comment]
It would be sweet to use some lightweight container that does not need a Docker Hub and all that cloud extra topping. I found [mbox](https://pdos.csail.mit.edu/archive/mbox/) that might prove useful.

**Comment by vidstige** [comment]
Sadly it does not have apt distribution, but it can just be downloaded + built at start of travis build.

**Comment by vidstige** [comment]
Alright, I tried mbox and it seems sweet. This is what I have so far

https://github.com/heartsucker/node-deb/compare/develop...vidstige:mbox-tests?expand=1

I just copied two test cases and they seem to work fine. When running under mbox, no files will actually be modified on your system, just a sandbox. :-) Also sudo seems to work just fine :+1:

Check out my branch and test like this `./mbox ./light-test.sh`

My idea is to run things under mbox instead of vagrant, but it was a little bit tangled with the unit tests so I tried it like this first. If you like it you (or me) can make a proper pr out of this.

**Comment by vidstige** [comment]
And just to connect the dots all the way to travis - When we can run without vagrant and VirtualBox, adding a TravisCI build is easy, I can do most of the work, but you need to enable the build on the official repo (here).

**Comment by heartsucker** [comment]
@vidstige I've enabled TravisCI on this repo. Is there a reason you're choosing `mbox` over `docker` as per #55?

**Comment by heartsucker** [comment]
That was phrased poorly, and what I meant was "is `mbox` being lightweight sufficient reason to choose it over `docker`?" I looked into it, and the last commit on `mbox` was 3 years ago, and I thought to use `docker` because it would allow me to test against various images of Debian and Ubuntu. It's not obvious if `mbox` supports this, and I'm inclined to think it does not. Also based on the popularity of `docker`, I'd have to reject a PR for `mbox`.

**Comment by vidstige** [comment]
No, only reason was that with mbox you don't really need anything extra, you can just checkout and run test suite. No need to install docker and so on. But I think docker would probably be better yes, but then again it will also be some more work,

**Comment by vidstige** [comment]
Good thing I just made a comment here before making a PR. :+1:

**Comment by vidstige** [comment]
One more advantage over docker is it's a bit faster, etc. If you're on a slow network for example downloading a docker image on a few gigs or whatever size they are can be a bit slower. `mbox` on the other side does not need the network at all, e.g. you can work on the train on cafés, etc. 

Perhaps the _tests_ and the _container_ can be separated somehow? Then we could have both. :-)

**Comment by heartsucker** [comment]
The thing with most of the test suite is that I really care about how it builds / operates *on an actual system* and that (I think) would be different under `mbox`. With docker, I'm aiming to set it up to have systemd and all the other things running so we can test some of the more complex features.

**Comment by heartsucker** [comment]
This is fixed in the `testing` branch and will eventually get merged into develop. Closing to prevent wasted work from anyone.
