### ISSUE TITLE
Cannot Get Real Working Directory

### ISSUE THREAD

**Issue by nprail** [heartsucker/node-deb#65]
I have built a Node.js CLI packaged with `node-deb`. It fails to create a `tmp` folder because of permissions errors because it thinks that the current working directory is `/usr/share/$app/app` instead of `/home/$user`. I see why it is doing this but I can't figure out a workaround (aside from running with `sudo`). Any help would be appreciated. 

I am using `var tmpDir = process.cwd() + '/tmp'` to set the `tmp` directory location. I've also tried simply `var tmpDir = 'tmp'` and `var tmpDir = __dirname + '/tmpDir'` but it always comes out with this directory: `/usr/share/$app/app`. Not `/hone/$user/tmp`. It works just fine when installed normally with NPM.

**Comment by heartsucker** [comment]
Heya @nprail 

Thanks for reporting this.

I did a workaround for the `node-deb` tool itself, but somehow never thought to port that to the main package.

```bash
#!/bin/bash
# This file was autogenerated by node-deb {{ node_deb_version }}
set -e
set -o pipefail

/usr/share/{{ node_deb_package_name }}/app/node-deb "$@"
```

Set your `package.json` to have
```json
{
  "node_deb": {
    "templates": {
      "executable": "/path/to/that/snippet"
    }
  }
}
```

This should get you up and running, and in the mean time I'll work on a more permanent fix.

**Comment by nprail** [comment]
That snippet didn't help. Or, I'm doing it wrong. 
I'm getting this error: 
```
/usr/bin/mc: line 6: /usr/share/mc-cli/app/bin/minecraft-cli.js: Permission denied
```

**Comment by heartsucker** [comment]
Ah, sorry. You need to add

```
#!/usr/bin/env node
```

to the top of the file and then `chmod 0755` the file so that it is executable.

**Comment by nprail** [comment]
It works! Thanks! Can `chmod 0755` happen during the installation?

**Comment by nprail** [comment]
I setup a `postinst` script in the `package.json` and it now works correctly! Thanks for the help! 

Should I close the issue now or wait until you port the workaround?

**Comment by heartsucker** [comment]
Could you leave it open so if others come around with the same issue they
can see the work around? I'll close it when the fix gets merged into
develop.

Am 22.04.2017 4:14 nachm. schrieb "Noah Prail" <notifications@github.com>:
