### ISSUE TITLE
Default template doesn't use the generated executable

### ISSUE THREAD

**Issue by zhiwei-nu** [heartsucker/node-deb#70]
The default `systemd` file uses:
```
ExecStart=/usr/share/{{ node_deb_package_name }}/app/{{ daemon_entrypoint }}
```
which seems weird, and would make more sense if the executable in the `bin` folder was used instead.

Close this if this is intended behavior, I'm working around with my own template `systemd` file now :)

**Comment by heartsucker** [comment]
It doesn't do it because presumably you'd want some special things to happen on the CLI tool that don't happen on the daemon, like preemptively passing a `--no-detach` flag or something. Do you have a specific use case where that is necessary?

**Comment by zhiwei-nu** [comment]
Ah, I see the rationale of it now and I believe your reasons are valid! You may close this whenever :)
