### ISSUE TITLE
Dereference symbolic links when copying node_modules

### ISSUE THREAD

**Issue by zhiwei-nu** [heartsucker/node-deb#71]
Right now `cp -rf` is used when install strategy is `copy`, but this fails if the installed module is local (e.g. installed via `npm install ../shared_module`), because the symbolic link that results will not resolve to anywhere in the built deb.

A quick and easy solution for this is to use `cp -rfL` instead which dereferences the symlink

**Comment by Skywalker13** [comment]
This changes breaks `autogypi` in my case and the `.bin/` directory... :-(
